# Generated by Django 4.2.4 on 2023-11-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumsper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(default='profile_img/default_profile_pic.png', upload_to='profile_img/'),
        ),
    ]
