# Generated by Django 4.2.4 on 2023-11-25 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumsper', '0003_comment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='job_profile',
            field=models.CharField(default='Under Graduate', max_length=20),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('image', models.ImageField(upload_to='event/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='data')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
