# Generated by Django 4.2.4 on 2023-11-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumsper', '0004_account_job_profile_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.CharField(default='Hey There, I am here useing AlumniSphere', max_length=60),
        ),
    ]
