# Generated by Django 4.2.4 on 2023-11-26 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumsper', '0006_eventcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='alumsper.event'),
        ),
    ]
